### ISSUE TITLE
BioPython is not automatically installed before this

### ISSUE THREAD

**Issue by niemasd** [veg/BioExt#23]
I was trying to install HIV-TRACE (`pip3 install hivtrace`) on my Mac OS X 10.13.5 machine running Python 3.7 (installed using Homebrew), and I encountered an error when installing biopython-extensions claiming that `Bio` was not found. I then tried installing just biopython-extensions (`pip3 install biopython-extensions`), and I got the same error:

```
Collecting biopython-extensions
  Using cached https://files.pythonhosted.org/packages/fa/28/5e0bd6b732f6513124634276f3fb20b358ae04b2f4c4db69b3629c1452b0/biopython-extensions-0.18.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1j/tpv1t3qs5jg0w5rsbc364mpc0000gn/T/pip-install-46d6dehb/biopython-extensions/setup.py", line 9, in <module>
        from BioExt.references._factory import _installrefdirs
      File "/private/var/folders/1j/tpv1t3qs5jg0w5rsbc364mpc0000gn/T/pip-install-46d6dehb/biopython-extensions/BioExt/references/__init__.py", line 6, in <module>
        from BioExt.references._factory import _refdir, _reffactory
      File "/private/var/folders/1j/tpv1t3qs5jg0w5rsbc364mpc0000gn/T/pip-install-46d6dehb/biopython-extensions/BioExt/references/_factory.py", line 12, in <module>
        from BioExt.references._lazyseq import _lazyseq
      File "/private/var/folders/1j/tpv1t3qs5jg0w5rsbc364mpc0000gn/T/pip-install-46d6dehb/biopython-extensions/BioExt/references/_lazyseq.py", line 6, in <module>
        from Bio import SeqIO
    ModuleNotFoundError: No module named 'Bio'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/1j/tpv1t3qs5jg0w5rsbc364mpc0000gn/T/pip-install-46d6dehb/biopython-extensions/
```

I then installed BioPython manually first (`pip3 install biopython`) and *then* installed this (`pip3 install biopython-extensions`), and it failed to install elsewhere (I posted [a separate Issue](https://github.com/veg/BioExt/issues/24) as it's a separate problem), but at least it didn't give this error anymore. Thus, I think that, for some reason, the `pip3 install biopython-extensions` command isn't automatically triggering installing BioPython. I checked your `setup.py` file and you do indeed include it in the `install_requires` list, so I'm not sure what's causing the issue.

**Comment by niemasd** [comment]
Note that the issue is identical in the default Python 2 installed on my Mac (Python 2.7.15), so this issue (unlike the other one) does not seem to be a Python 3.7 issue:

**Comment by niemasd** [comment]
I think the issue is here: https://github.com/veg/BioExt/blob/master/setup.py#L10

```bash
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1j/tpv1t3qs5jg0w5rsbc364mpc0000gn/T/pip-install-2ntm5k/biopython-extensions/setup.py", line 9, in <module>
        from BioExt.references._factory import _installrefdirs
      File "BioExt/references/__init__.py", line 6, in <module>
        from BioExt.references._factory import _refdir, _reffactory
      File "BioExt/references/_factory.py", line 12, in <module>
        from BioExt.references._lazyseq import _lazyseq
      File "BioExt/references/_lazyseq.py", line 6, in <module>
        from Bio import SeqIO
    ImportError: No module named Bio
```

This import calls another import that is in BioPython. I wonder if it'll fix it if the `install_requires` list is placed earlier? Otherwise I think the imports would need to be restructured to fix the issue

**Comment by stevenweaver** [comment]
Dear @niemasd, 

Thank you for opening this issue. Thanks to your recommendation, the package no will longer need biopython to be installed first. However, `bioext` also requires `numpy` and `Cython` before pip install. The supported `python` solution to this issue is to create a `requires.txt` file for deployment. I will do this now. 

I
