### ISSUE TITLE
bealign fails to run due to removal of Bio.Alphabet

### ISSUE THREAD

**Issue by sdwfrost** [veg/BioExt#36]
Running bealign with the latest Biopython throws the following error:

```
Traceback (most recent call last):
  File "/opt/conda/bin/bealign", line 14, in <module>
    from BioExt.io import BamIO
  File "/opt/conda/lib/python3.8/site-packages/BioExt/io/BamIO/__init__.py", line 7, in <module>
    from BioExt.io import _SamBamIO
  File "/opt/conda/lib/python3.8/site-packages/BioExt/io/_SamBamIO.py", line 8, in <module>
    from Bio.Alphabet import single_letter_alphabet
  File "/opt/conda/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```

**Comment by stevenweaver** [comment]
Dear @sdwfrost, 

The issue should be resolved in version 0.19.8.

Best,
Steven
