### ISSUE TITLE
problem with install

### ISSUE THREAD

**Issue by robertcharette** [veg/BioExt#37]
I am trying to install bioext. I succeeded on Mac OSX but under linux I get the following message

Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    tn93_extension = cythonize([
  File "/usr/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 963, in cythonize
    ctx = c_options.create_context()
  File "/usr/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 596, in create_context
    return Context(self.include_path, self.compiler_directives,
  File "/usr/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 80, in __init__
    from . import Builtin, CythonScope
  File "/usr/lib/python3.8/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
    from .UtilityCode import CythonUtilityCode
  File "/usr/lib/python3.8/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
    from .TreeFragment import parse_from_strings, StringParseContext
  File "/usr/lib/python3.8/site-packages/Cython/Compiler/TreeFragment.py", line 21, in <module>
    from . import Parsing
  File "/usr/lib/python3.8/site-packages/Cython/Compiler/Parsing.py", line 31, in <module>
    from .ModuleNode import ModuleNode
  File "/usr/lib/python3.8/site-packages/Cython/Compiler/ModuleNode.py", line 3216, in <module>
    capsule_utility_code = UtilityCode.load("Capsule")
  File "/usr/lib/python3.8/site-packages/Cython/Compiler/Code.py", line 368, in load
    raise ValueError("More than one filename match found for utility code " + util_code_name)
ValueError: More than one filename match found for utility code Capsule

Any explanation ?

**Comment by spond** [comment]
Dear @robertcharette,

This probably has something to do with multiple versions of Conda/Python on your Linux system (e.g . https://github.com/cython/cython/issues/3842) 

I would suggest using a clean Python virtual env to avoid these types of issues (https://docs.python.org/3/tutorial/venv.html)

Best,
Sergei

**Comment by robertcharette** [comment]
Thank you very much. Using a Vvirtual environment solved the issue

**Comment by robertcharette** [comment]
Thank you very much. Using a virtual environment solved the issue.
