### ISSUE TITLE
bealign not work after installation sucessfully.help!

### ISSUE THREAD

**Issue by samsonfengyi** [veg/BioExt#54]
Traceback (most recent call last):
  File "/home/xxxxx/.local/bin/bealign", line 143, in <module>
    add_reference(parser, '-r', '--reference')
  File "/home/xxxxx/.local/lib/python3.10/site-packages/BioExt/args/__init__.py", line 33, in add_reference
    'HXB2_env': hxb2.env,
AttributeError: 'hxb2' object has no attribute 'env'

**Comment by niemasd** [comment]
@spond @stevenweaver I'm getting the same error message on a fresh Ubuntu install:

```bash
apt-get update && apt-get -y upgrade
DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y cmake g++ gcc git make python3 python3-pip wget
python3 -m pip install --upgrade pip
pip3 install bioext
bealign -h
```

The above produces the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/bealign", line 143, in <module>
    add_reference(parser, '-r', '--reference')
  File "/usr/local/lib/python3.10/dist-packages/BioExt/args/__init__.py", line 33, in add_reference
    'HXB2_env': hxb2.env,
AttributeError: 'hxb2' object has no attribute 'env'
```

**Comment by stevenweaver** [comment]
The issue should be resolved in 0.21.5.

**Comment by niemasd** [comment]
Unfortunately, I don't think that fixed it. I tried creating a fresh Ubuntu environment again (I'm using a GitHub Codespace with Ubuntu 22.04 as the base image), and the same commands as earlier results in the same error message. I can confirm that I'm on the new 0.21.5 version on PyPI (so it's not using the previous version I was using), as `pip show bioext` prints the following:

```
Name: bioext
Version: 0.21.5
Summary: Misc utilities and definitions not included or hidden in BioPython
Home-page: http://github.com/veg/bioext
Author: N Lance Hepler
Author-email: nlhepler@gmail.com
License: GNU GPL version 3
Location: /usr/local/lib/python3.10/dist-packages
Requires: biopython, joblib, numpy, pysam, scipy, six
Required-by:
```

**Comment by niemasd** [comment]
The newest version on PyPI as of now (0.21.7) fixes the issue! Thanks so much!

```bash
$ pip show bioext
Name: bioext
Version: 0.21.7
Summary: Misc utilities and definitions not included or hidden in BioPython
Home-page: http://github.com/veg/bioext
Author: N Lance Hepler
Author-email: nlhepler@gmail.com
License: GNU GPL version 3
Location: /usr/local/lib/python3.10/dist-packages
Requires: biopython, joblib, numpy, pysam, scipy, six
Required-by:
```

```bash
$ bealign -h
usage: bealign [-h] [-r REFERENCE] [-e EXPECTED_IDENTITY] [-a ALPHABET] [-m SCOREMATRIX] [-D DISCARD] [-R] [-S] [-q] [-v] [-K] INPUT OUTPUT

align sequences to a reference using a codon alignment algorithm and output to a BAM file

positional arguments:
  INPUT                 INPUT FASTA file
  OUTPUT                send BAM to OUTPUT

options:
  -h, --help            show this help message and exit
  -r REFERENCE, --reference REFERENCE
                        REFERENCE FASTA file or {HXB2_env, HXB2_gag, HXB2_int, HXB2_nef, HXB2_pol, HXB2_pr, HXB2_prrt, HXB2_rev, HXB2_rt, HXB2_tat, HXB2_vif, HXB2_vpr, HXB2_vpu,
                        NL4-3_prrt, CoV2-3C, CoV2-E, CoV2-endornase, CoV2-exonuclease, CoV2-helicase, CoV2-leader, CoV2-methyltransferase, CoV2-M, CoV2-N, CoV2-nsp10, CoV2-nsp2,
                        CoV2-nsp3, CoV2-nsp4, CoV2-nsp6, CoV2-nsp7, CoV2-nsp8, CoV2-nsp9, CoV2-ORF10, CoV2-ORF1a, CoV2-ORF1b, CoV2-ORF3a, CoV2-ORF5, CoV2-ORF6, CoV2-ORF7a, CoV2-ORF7b,
                        CoV2-ORF8, CoV2-RdRp, CoV2-S}
  -e EXPECTED_IDENTITY, --expected-identity EXPECTED_IDENTITY
                        discard sequences that are insufficiently identical to the reference
  -a ALPHABET, --alphabet ALPHABET
                        perform an alignment using one of {amino, dna, codon} [default=codon]
  -m SCOREMATRIX, --score-matrix SCOREMATRIX
                        parameterize using one of {BLOSUM62, DNA65, DNA70, DNA80, DNA88, DNA95, HIV_BETWEEN_F, PAM200, PAM250} [default=BLOSUM62]
  -D DISCARD, --discard DISCARD
                        discarded sequences are sent to DISCARD
  -R, --reverse-complement
                        also align the reverse complement of each query sequence, returning it if the alignment is superior
  -S, --no-sort         do NOT sort the resulting BAM file [the default is to sort]
  -q, --quiet           do not print status update messages
  -v, --version         print version information and exit
  -K, --keep-reference  include the reference sequence as the first one in the resulting BAM file [the default is to strip it]
```

Not super critical, but `bealign -v` shows the wrong version number (maybe it needs to be updated in multiple places and got out-of-sync in recent updates):

```bash
$ bealign -v
BioExt version 0.19.0
```
